### ISSUE TITLE
Error message when not using --keep: "rm: cannot remove ‘keepsamples.incl’: No such file or directory"

### ISSUE THREAD

**Issue by robkar** [ColemanResearchGroup/summaryLD#5]
Suggest to change `rm` to `rm -f` at
https://github.com/ColemanResearchGroup/summaryLD/blob/015572eddb681a1611de0ef6be0363a096ef8ee0/GenerateLDStore.bash#L543 so that missing files are silently ignored.

**Comment by JoniColeman** [comment]
Added in  commit 7e33a07
